quantum_datapath: "/mnt/mntsdb/genai/10_623_final_project/QCDGE.xyz"
outpath: "/mnt/mntsdb/genai/10_623_final_project/training/training_runs"
features_path: "/mnt/mntsdb/genai/10_623_final_project/low_quality_mol_features.pkl"
n_epochs: 5
batch_size: 8 
lr: 4e-4
val_size: 0.2
test_size: 0.0
n_devs: 1
wandb_project: "GenAIProject"

model_config:
  n_transformer_blocks: 8
  n_heads: 16
  d_model: 512
  timesteps: 1000